/* ============================================================
   DualDungeonGen — CONTENT LIBRARY (offline, bilingual)
   SRD monster bank + themed room prose / feats / traps / loot.
   The generator (03) does the encounter math; this file supplies
   the *content*. Player-facing `see` text is sensory only — it
   never names monsters or reveals secrets (skill rule).
   ============================================================ */
(function (root) {
  "use strict";
  var DDG = root.DDG || (root.DDG = {});

  // ---- SRD monster bank -------------------------------------------------
  // id: {en, es, cr, tok(2-3 letters for the map token)}
  var MON = {
    flying_sword:   { en: "Flying Sword", es: "Espada Voladora", cr: 0.25, tok: "SW" },
    animated_armor: { en: "Animated Armor", es: "Armadura Animada", cr: 1, tok: "AA" },
    helmed_horror:  { en: "Helmed Horror", es: "Horror con Yelmo", cr: 4, tok: "HH" },
    rug:            { en: "Rug of Smothering", es: "Alfombra Asfixiante", cr: 2, tok: "RUG" },
    mimic:          { en: "Mimic", es: "Mímico", cr: 2, tok: "MIM" },
    flameskull:     { en: "Flameskull", es: "Calavera Flamígera", cr: 4, tok: "FSK" },
    gray_ooze:      { en: "Gray Ooze", es: "Limo Gris", cr: 0.5, tok: "OOZ" },
    ochre_jelly:    { en: "Ochre Jelly", es: "Gelatina Ocre", cr: 2, tok: "OJ" },

    skeleton:   { en: "Skeleton", es: "Esqueleto", cr: 0.25, tok: "SK" },
    zombie:     { en: "Zombie", es: "Zombi", cr: 0.25, tok: "ZO" },
    ghoul:      { en: "Ghoul", es: "Necrófago", cr: 1, tok: "GHL" },
    ghast:      { en: "Ghast", es: "Necrófago superior", cr: 2, tok: "GHA" },
    specter:    { en: "Specter", es: "Espectro", cr: 1, tok: "SPC" },
    shadow:     { en: "Shadow", es: "Sombra", cr: 0.5, tok: "SHD" },
    wight:      { en: "Wight", es: "Wight", cr: 3, tok: "WI" },
    wraith:     { en: "Wraith", es: "Aparición", cr: 5, tok: "WR" },
    will_o_wisp:{ en: "Will-o'-Wisp", es: "Fuego Fatuo", cr: 2, tok: "WSP" },
    minotaur_sk:{ en: "Minotaur Skeleton", es: "Esqueleto Minotauro", cr: 2, tok: "MSK" },

    giant_rat:  { en: "Giant Rat", es: "Rata Gigante", cr: 0.125, tok: "RAT" },
    swarm_rats: { en: "Swarm of Rats", es: "Enjambre de Ratas", cr: 0.25, tok: "SWR" },
    giant_bat:  { en: "Giant Bat", es: "Murciélago Gigante", cr: 0.25, tok: "BAT" },
    giant_spider:{ en: "Giant Spider", es: "Araña Gigante", cr: 1, tok: "SPD" },
    ettercap:   { en: "Ettercap", es: "Ettercap", cr: 2, tok: "ETC" },
    dire_wolf:  { en: "Dire Wolf", es: "Lobo Terrible", cr: 1, tok: "DW" },
    brown_bear: { en: "Brown Bear", es: "Oso Pardo", cr: 1, tok: "BR" },
    cave_bear:  { en: "Cave Bear", es: "Oso de las Cavernas", cr: 2, tok: "CB" },
    owlbear:    { en: "Owlbear", es: "Búho-oso", cr: 3, tok: "OWL" },
    giant_toad: { en: "Giant Toad", es: "Sapo Gigante", cr: 1, tok: "TD" },
    grick:      { en: "Grick", es: "Grick", cr: 2, tok: "GK" },
    swarm_insects:{ en: "Swarm of Insects", es: "Enjambre de Insectos", cr: 0.5, tok: "SWI" },
    giant_boar: { en: "Giant Boar", es: "Jabalí Gigante", cr: 1, tok: "BO" },

    cultist:    { en: "Cultist", es: "Cultista", cr: 0.125, tok: "CU" },
    acolyte:    { en: "Acolyte", es: "Acólito", cr: 0.25, tok: "AC" },
    thug:       { en: "Thug", es: "Matón", cr: 0.5, tok: "TH" },
    bandit:     { en: "Bandit", es: "Bandido", cr: 0.125, tok: "BN" },
    berserker:  { en: "Berserker", es: "Berserker", cr: 2, tok: "BSK" },
    cult_fanatic:{ en: "Cult Fanatic", es: "Fanático de Culto", cr: 2, tok: "CF" },
    priest:     { en: "Priest", es: "Sacerdote", cr: 2, tok: "PR" }
  };

  // Helper to build a full mon display string + token from a bank id + count.
  function monEntry(id, count) {
    var m = MON[id]; if (!m) return null;
    return { id: id, count: count || 1, cr: m.cr, en: m.en, es: m.es, tok: m.tok };
  }

  // ---- themes -----------------------------------------------------------
  // Each role -> array of prose blocks. Generator picks one per room and
  // scales monsters (from `pools`) to the party's budget band.
  var THEMES = {
    crafters: {
      key: "crafters",
      name: { en: "The {ord} Guild of the Broken Cog", es: "El Gremio {ord} del Engranaje Roto" },
      subtitle: { en: "A silent guildhall where the tools have turned on their makers.", es: "Un gremio en silencio donde las herramientas se volvieron contra sus dueños." },
      badge: { en: "Crafters' Grounds", es: "Recinto de Artesanos" },
      pools: { entry: ["flying_sword", "animated_armor"], work: ["rug", "mimic", "gray_ooze", "flying_sword", "animated_armor"], climax: ["helmed_horror", "flameskull"], hazard: ["ochre_jelly", "gray_ooze", "swarm_insects"] },
      feats: { entry: ["crest", "desk", "cases"], work: [["looms", "tapestry"], ["kiln", "anvil", "bellows"], ["benches", "lathe"], ["shelves", "crates", "vat"]], climax: ["columns", "plinth"], secret: ["deskbig", "bookshelf", "safe"], hazard: ["barrels", "vat"] },
      overview: [
        { en: "The Crafters' Guild has gone quiet. Its Guildmaster tried to bind a living spirit into a masterwork guardian — to protect, and secretly to sell, the guild's crown achievement. The binding half-failed and the spirit's animating force bled into every tool in the hall. Find out what happened, survive the grounds, and secure the masterwork — or free the spirit and let the whole place fall still.",
          es: "El Gremio de Artesanos enmudeció. Su Maestra intentó atar un espíritu vivo a un guardián maestro — para proteger, y en secreto vender, la obra cumbre del gremio. La atadura falló a medias y la fuerza animadora se filtró en cada herramienta del salón. Averigua qué pasó, sobrevive al recinto y asegura la obra maestra — o libera al espíritu y deja que todo se detenga." }
      ],
      villains: [{ en: "the artificer Ottavia Brenn", es: "la artífice Ottavia Brenn" }, { en: "Master Halden Vex", es: "el Maestro Halden Vex" }],
      macguffin: [{ en: "the Masterwork Automaton-Heart", es: "el Corazón-Autómata Maestro" }, { en: "the guild's crown commission", es: "la obra cumbre del gremio" }]
    },

    crypt: {
      key: "crypt",
      name: { en: "The {ord} Crypt of Ashen Vigil", es: "La Cripta {ord} de la Vigilia Cenicienta" },
      subtitle: { en: "A tomb that will not stay sealed, and the dead keep its old duty.", es: "Una tumba que no permanece sellada, y los muertos cumplen su vieja tarea." },
      badge: { en: "Undead Tomb", es: "Tumba de No-muertos" },
      pools: { entry: ["skeleton", "zombie"], work: ["ghoul", "shadow", "specter", "skeleton", "giant_rat"], climax: ["wight", "wraith", "flameskull", "minotaur_sk"], hazard: ["gray_ooze", "swarm_rats", "shadow"] },
      feats: { entry: ["altar", "brazier"], work: [["sarcophagus"], ["columns", "brazier"], ["shelves", "rubble"], ["altar", "brazier"]], climax: ["sarcophagus", "throne"], secret: ["deskbig", "safe"], hazard: ["pool", "rubble"] },
      overview: [
        { en: "The old crypt's wards have failed. Something beneath has woken the interred and set them to a ritual half-remembered from life. The tomb's grave-lord waits at the heart, and its rite is nearly complete. Cut down what walks, learn who broke the seal, and end the rite — by blade, by fire, or by laying the grave-lord to rest.",
          es: "Las guardas de la vieja cripta han caído. Algo en lo profundo ha despertado a los sepultados y los ha puesto a un rito a medias recordado. El señor de las tumbas aguarda en el corazón, y su rito está casi completo. Abate lo que camina, averigua quién rompió el sello y detén el rito — con filo, con fuego, o dando descanso al señor de las tumbas." }
      ],
      villains: [{ en: "the grave-lord Nethyros", es: "el señor de las tumbas Nethyros" }, { en: "the ashen custodian", es: "el custodio ceniciento" }],
      macguffin: [{ en: "the Seal of Ashen Vigil", es: "el Sello de la Vigilia Cenicienta" }, { en: "the grave-lord's phylactery", es: "el filacteria del señor de las tumbas" }]
    },

    cave: {
      key: "cave",
      name: { en: "The {ord} Warren of Gullet Deep", es: "La Madriguera {ord} del Abismo Fauces" },
      subtitle: { en: "A living cave where every dark hollow has teeth.", es: "Una cueva viva donde cada hueco oscuro tiene dientes." },
      badge: { en: "Beast Warren", es: "Madriguera Bestial" },
      pools: { entry: ["giant_rat", "giant_bat", "swarm_rats"], work: ["giant_spider", "dire_wolf", "brown_bear", "giant_toad", "ettercap"], climax: ["owlbear", "cave_bear", "grick"], hazard: ["gray_ooze", "swarm_insects", "giant_toad"] },
      feats: { entry: ["stalagmites", "rubble"], work: [["stalagmites"], ["pool", "rubble"], ["rubble", "barrels"], ["stalagmites", "pool"]], climax: ["stalagmites", "rubble"], secret: ["crates", "safe"], hazard: ["pool", "stalagmites"] },
      overview: [
        { en: "Livestock and travelers have been vanishing near the old cave mouth. Inside, a den has grown fat and territorial, and something larger rules the deepest chamber. Track the beasts to their warren, thin the pack, and deal with what nests at the bottom — kill it, drive it off, or take its hoard and run.",
          es: "Ganado y viajeros desaparecen cerca de la vieja boca de la cueva. Dentro, una guarida ha crecido gorda y territorial, y algo mayor gobierna la cámara más honda. Sigue el rastro de las bestias hasta la madriguera, diezma la manada y ocúpate de lo que anida al fondo — mátalo, ahuyéntalo, o toma su tesoro y corre." }
      ],
      villains: [{ en: "the pack-mother", es: "la madre de la manada" }, { en: "the deep-den brute", es: "el bruto de la guarida honda" }],
      macguffin: [{ en: "the beast's hoard", es: "el tesoro de la bestia" }, { en: "a swallowed heirloom", es: "una reliquia tragada" }]
    },

    cult: {
      key: "cult",
      name: { en: "The {ord} Sanctum of the Hollow Choir", es: "El Santuario {ord} del Coro Hueco" },
      subtitle: { en: "A hidden shrine mid-rite, and its congregation does not want witnesses.", es: "Un santuario oculto en pleno rito, y su congregación no quiere testigos." },
      badge: { en: "Cult Sanctum", es: "Santuario de Culto" },
      pools: { entry: ["cultist", "bandit", "acolyte"], work: ["thug", "cultist", "acolyte", "berserker", "giant_spider"], climax: ["cult_fanatic", "priest", "berserker"], hazard: ["swarm_insects", "shadow", "gray_ooze"] },
      feats: { entry: ["altar", "brazier"], work: [["table", "cases"], ["beds", "barrels"], ["cauldron", "shelves"], ["altar", "brazier"]], climax: ["altar", "columns", "brazier"], secret: ["deskbig", "bookshelf", "safe"], hazard: ["cauldron", "pool"] },
      overview: [
        { en: "A cell of the Hollow Choir has taken over a warren below the streets and begun a binding rite. Left alone, it opens a door that should stay shut. Get in past the doorwardens, unravel who leads the choir, and stop the rite at the sanctum — silence the celebrant, or shatter the focus of the ritual.",
          es: "Una célula del Coro Hueco ha ocupado una madriguera bajo las calles y comenzado un rito de atadura. Sin oposición, abre una puerta que debería seguir cerrada. Entra sorteando a los guardianes de la puerta, descubre quién dirige el coro y detén el rito en el santuario — silencia al oficiante, o destroza el foco del ritual." }
      ],
      villains: [{ en: "the celebrant Vell", es: "el oficiante Vell" }, { en: "Mother Sil of the Choir", es: "la Madre Sil del Coro" }],
      macguffin: [{ en: "the Hollow Focus", es: "el Foco Hueco" }, { en: "the choir's binding-stone", es: "la piedra de atadura del coro" }]
    }
  };

  // ---- room prose blocks by role (shared where possible) ----------------
  // Player `see` = sensory only. `tac` matches the role, not a specific mon.
  var ROLE_PROSE = {
    crafters: {
      entry: [{ name: { en: "Guild Reception", es: "Recepción del Gremio" },
        see: { en: "A once-proud entry hall. A brass crest is inlaid in the floor, a reception desk sits dusty, and glass cases display prize goods. Something along the walls shifts on its mounts.", es: "Un vestíbulo antes orgulloso. Un escudo de latón incrustado en el piso, un mostrador polvoriento y vitrinas con piezas premiadas. Algo en las paredes se mueve en sus soportes." },
        loot: { en: "A display brooch (25 gp) and the guild seal that opens the inner strongboxes.", es: "Un broche de vitrina (25 po) y el sello del gremio que abre las cajas fuertes interiores." },
        tac: { en: "Warm-up fight. Let it teach the ‘animated tools’ theme before the real threats — the attackers harry and retreat rather than press.", es: "Combate de calentamiento. Que enseñe el tema de ‘herramientas animadas’ antes de las amenazas reales — los atacantes hostigan y se retiran en vez de presionar." } }],
      work: [
        { name: { en: "Loom Hall", es: "Salón de Telares" }, see: { en: "Great looms strung with shimmering thread. A huge half-finished tapestry hangs on the far wall — swaying, though there is no wind.", es: "Grandes telares con hilos que relucen. Un enorme tapiz a medio terminar cuelga al fondo — se mece, aunque no hay viento." },
          trap: { en: "Loom-wire tripwire at the threshold — DC 13 Perception to spot; DC 13 Dex or 1d10 slashing and restrained (DC 13 Str to break free).", es: "Alambre de telar en el umbral — CD 13 Percepción para verlo; CD 13 Des o 1d10 cortante y apresado (CD 13 Fue para soltarse)." },
          loot: { en: "A bolt of enchanted cloth — 50 gp, or the raw material for a Cloak of Protection.", es: "Un rollo de tela encantada — 50 po, o material para una Capa de Protección." },
          tac: { en: "The ambusher drops on the first PC to reach the looms — blinding and grappling. The tripwire softens the party on the way in.", es: "El emboscador cae sobre el primer PJ que llega a los telares — cegando y apresando. El alambre ablanda al grupo al entrar." } },
        { name: { en: "The Smithy", es: "La Fragua" }, see: { en: "Cold anvils, a bellows, and a great kiln still burning with unnatural blue-white fire. Heat rolls off the coals in waves.", es: "Yunques fríos, un fuelle y un gran horno que aún arde con fuego blanco-azulado antinatural. El calor sube de las brasas en oleadas." },
          trap: { en: "Bellows flame-jet — a pressure plate by the kiln; DC 15 Dex or 2d10 fire in a 10-ft line. The coals are difficult, burning terrain (1d6 fire).", es: "Chorro de llama del fuelle — placa de presión junto al horno; CD 15 Des o 2d10 fuego en línea de 3 m. Las brasas son terreno difícil y ardiente (1d6 fuego)." },
          loot: { en: "Masterwork smith's tools; a +1 dagger cooling on the anvil.", es: "Herramientas de herrero de obra maestra; una daga +1 enfriándose en el yunque." },
          tac: { en: "The kiln anchors the fire-threat here — dousing it (holy water, cold, dispel magic) stops it reforming AND weakens the climax guardian. Reward players who connect the two.", es: "El horno ancla la amenaza de fuego — apagarlo (agua bendita, frío, disipar magia) impide que se reforme Y debilita al guardián del clímax. Premia a quien lo deduzca." } },
        { name: { en: "Woodshop", es: "Carpintería" }, see: { en: "Sawdust and lathes. Workbenches heaped with tools — and one fine, oddly pristine chest sitting alone on the central bench.", es: "Aserrín y tornos. Bancos cubiertos de herramientas — y un cofre fino, extrañamente impecable, solo sobre el banco central." },
          trap: { en: "Lathe swinging-blade — tampering with the far bench triggers it; DC 14 Dex or 2d8 slashing.", es: "Cuchilla giratoria del torno — manipular el banco del fondo la activa; CD 14 Des o 2d8 cortante." },
          loot: { en: "Masterwork carpenter's tools; the real chest holds 120 gp and 2 potions of healing.", es: "Herramientas de carpintero de obra maestra; el cofre real guarda 120 po y 2 pociones de curación." },
          tac: { en: "The ambusher waits disguised, then grapples the looter with adhesive. The hidden way onward is on this room's far wall (DC 15 Investigation).", es: "El emboscador espera disfrazado y luego apresa al saqueador con su adhesivo. El paso oculto está en el muro del fondo (CD 15 Investigación)." } },
        { name: { en: "Material Vault", es: "Bodega de Materiales" }, see: { en: "Shelves of raw stock — ingots, timber, dyes — around a sunken etching-vat of green acid. Something shifts under its surface.", es: "Estantes de materia prima — lingotes, madera, tintes — en torno a una tina hundida de ácido verde. Algo se mueve bajo la superficie." },
          trap: { en: "Acid splash — the narrow ledge is DC 14 Dex or 2d6 acid (corrodes a nonmagical metal item −1).", es: "Salpicadura de ácido — el borde estrecho es CD 14 Des o 2d6 ácido (corroe un objeto de metal no mágico −1)." },
          loot: { en: "A locked strongbox (DC 15): 200 gp and a gold ingot (50 gp).", es: "Una caja fuerte cerrada (CD 15): 200 po y un lingote de oro (50 po)." },
          tac: { en: "The hazard plays dead as raw material, then lashes out — it corrodes weapons, so reward players who spot it first.", es: "El peligro se hace el muerto como material en bruto y luego ataca — corroe armas, así que premia a quien lo detecte primero." } },
        { name: { en: "Glassblowing Hall", es: "Sala de Soplado de Vidrio" }, see: { en: "A cold furnace and racks of half-blown glass, some pieces turning slowly as if on an unseen lathe.", es: "Un horno frío y estantes de vidrio a medio soplar, algunas piezas girando despacio como en un torno invisible." },
          trap: { en: "A rack of glass shards rigged to topple — DC 13 Perception; DC 14 Dex or 2d6 slashing.", es: "Un estante de esquirlas de vidrio listo para volcarse — CD 13 Percepción; CD 14 Des o 2d6 cortante." },
          loot: { en: "A masterwork glass lens (60 gp) and an unfinished wondrous focus.", es: "Una lente de vidrio de obra maestra (60 po) y un foco maravilloso sin terminar." },
          tac: { en: "The animated pieces swarm and shatter for a burst of slashing — brittle but fast; area damage clears them.", es: "Las piezas animadas enjambran y estallan en un golpe cortante — frágiles pero veloces; el daño de área las despeja." } },
        { name: { en: "Engraving Studio", es: "Taller de Grabado" }, see: { en: "Copper plates and burins laid in neat rows. Acid baths line one wall, their surface trembling.", es: "Planchas de cobre y buriles en hileras ordenadas. Cubas de ácido recorren un muro, su superficie temblando." },
          trap: { en: "Etching-acid overflow — DC 14 Dex crossing or 2d6 acid.", es: "Desborde de ácido de grabado — CD 14 Des al cruzar o 2d6 ácido." },
          loot: { en: "Engraving tools and a plate worth 70 gp; a scroll-case with the guild cipher.", es: "Herramientas de grabado y una plancha por 70 po; un tubo con la clave del gremio." },
          tac: { en: "The lurker hides among the plates and lashes at the first to reach the baths — corrosive, so protect metal gear.", es: "El acechador se oculta entre las planchas y ataca al primero que llega a las cubas — corrosivo, así que protege el equipo de metal." } }
      ],
      climax: [{ name: { en: "Masterwork Gallery", es: "Galería de Obras Maestras" }, see: { en: "Columns ring a raised plinth. On it rests the guild's crown achievement in brass and crystal. A tall sentinel stands over it, and its blank face turns toward you.", es: "Columnas rodean un pedestal elevado. Sobre él, la obra cumbre del gremio en latón y cristal. Un alto centinela lo custodia, y su rostro vacío gira hacia ti." },
        trap: { en: "Rune-glyph on the plinth — lifting the prize without the guild-word triggers it: DC 15 Dex, 3d6 force + alarm.", es: "Glifo en el pedestal — alzar el premio sin la palabra-gremio lo activa: CD 15 Des, 3d6 fuerza + alarma." },
        loot: { en: "The masterwork prize — a wondrous item — plus the guild's 500 gp treasure.", es: "El premio maestro — un objeto maravilloso — y el tesoro de 500 po del gremio." },
        tac: { en: "Climax. The guardian holds the plinth and focuses casters; it shrugs off common spells. If the work-room anchor was dealt with, it fights at disadvantage — the payoff for clever play.", es: "Clímax. El guardián protege el pedestal y se centra en los lanzadores; resiste los hechizos comunes. Si trataron el ancla de la sala de trabajo, ataca con desventaja — la recompensa por jugar con astucia." } }],
      secret: [{ name: { en: "Guildmaster's Study", es: "Estudio de la Maestra" }, see: { en: "Behind a false bookcase: a tidy study. A ledger lies open on the desk; a wall-safe hides a private prize.", es: "Tras una estantería falsa: un estudio ordenado. Un libro de cuentas abierto sobre el escritorio; una caja fuerte oculta un premio privado." },
        loot: { en: "The safe (guild seal or DC 15): 300 gp, an Alchemy Jug, a signet. The ledger names the buyer and the guild-word.", es: "La caja (sello o CD 15): 300 po, una Jarra de Alquimia, un sello. El libro nombra al comprador y la palabra-gremio." },
        tac: { en: "No fight. This room is the ‘why’: the ledger turns a crawl into a choice — sell the prize, destroy it, or free the spirit.", es: "Sin combate. Esta sala es el ‘porqué’: el libro convierte el saqueo en una decisión — vender el premio, destruirlo o liberar al espíritu." } }],
      hazard: [{ name: { en: "Storeroom", es: "Almacén" }, see: { en: "Stacked barrels and crates in the half-dark. The floor is slick underfoot and the air smells of rot.", es: "Barriles y cajas apilados en la penumbra. El suelo resbala y el aire huele a podredumbre." },
        trap: { en: "Weakened floorboards — DC 13 Perception; DC 13 Dex or fall 10 ft (1d6) into a debris pit.", es: "Tablas debilitadas — CD 13 Percepción; CD 13 Des o caída de 3 m (1d6) a un foso de escombros." },
        loot: { en: "Salvage worth 40 gp and a flask of alchemist's fire.", es: "Chatarra por 40 po y un frasco de fuego alquímico." },
        tac: { en: "Optional breather with a lurking hazard — an easy fight or a skippable room for pacing.", es: "Respiro opcional con un peligro al acecho — un combate fácil o una sala saltable para el ritmo." } }]
    }
  };
  // Reuse crafters prose shapes for other themes but reskin names/see per role.
  ROLE_PROSE.crypt = {
    entry: [{ name: { en: "Sealed Antechamber", es: "Antecámara Sellada" }, see: { en: "A cold vestibule of carved stone. Grave-dust lies thick, and the broken seal of the tomb hangs off the inner doors. Shapes stand too still against the walls.", es: "Un frío vestíbulo de piedra tallada. El polvo de tumba yace espeso, y el sello roto de la cripta cuelga de las puertas interiores. Formas demasiado quietas contra los muros." }, loot: { en: "Funerary silver (25 gp) and a bronze key marked with the tomb's sigil.", es: "Plata funeraria (25 po) y una llave de bronce con el sigilo de la tumba." }, tac: { en: "Warm-up. The dead here are slow and clumsy — teach the party that undead keep coming until put down for good.", es: "Calentamiento. Los muertos aquí son lentos y torpes — enseña que los no-muertos no paran hasta ser abatidos del todo." } }],
    work: [
      { name: { en: "Niche Gallery", es: "Galería de Nichos" }, see: { en: "Wall-niches hold shrouded remains, tier on tier. The shadows between them do not fall quite right.", es: "Nichos en los muros guardan restos amortajados, hilera sobre hilera. Las sombras entre ellos no caen del todo bien." }, trap: { en: "Collapsing niche — disturbing the wrong shelf drops masonry; DC 14 Dex or 2d8 bludgeoning.", es: "Nicho que se derrumba — perturbar el estante erróneo suelta mampostería; CD 14 Des o 2d8 contundente." }, loot: { en: "Grave-goods worth 60 gp; a vial of holy water tucked in a shroud.", es: "Ofrendas por 60 po; un vial de agua bendita entre las mortajas." }, tac: { en: "The lurkers cling to the dark and drain the isolated — they hate light, so reward torches and radiant damage.", es: "Los acechadores se pegan a la oscuridad y drenan al aislado — odian la luz, así que premia antorchas y daño radiante." } },
      { name: { en: "Reliquary", es: "Relicario" }, see: { en: "Stone sarcophagi under a low vaulted ceiling. One lid sits askew, scraped as if from the inside.", es: "Sarcófagos de piedra bajo una bóveda baja. Una tapa está torcida, raspada como desde dentro." }, trap: { en: "Poison-needle latch on the reliquary — DC 15 Investigation; DC 15 Con or 2d6 poison.", es: "Cerrojo de aguja envenenada en el relicario — CD 15 Investigación; CD 15 Con o 2d6 veneno." }, loot: { en: "A silver holy symbol (75 gp) and a Potion of Healing.", es: "Un símbolo sagrado de plata (75 po) y una Poción de Curación." }, tac: { en: "The occupant bursts from the sarcophagus when the lid is touched — a sudden spike to punish greed.", es: "El ocupante irrumpe del sarcófago al tocar la tapa — un pico súbito para castigar la codicia." } },
      { name: { en: "Ossuary", es: "Osario" }, see: { en: "Bones stacked floor to ceiling in careful patterns. A cold draft stirs them, and they whisper as they settle.", es: "Huesos apilados del suelo al techo en patrones cuidados. Una corriente fría los agita, y susurran al asentarse." }, trap: { en: "Bone-slide — the far arch is rigged; DC 14 Dex or buried for 1d6 bludgeoning and restrained.", es: "Alud de huesos — el arco del fondo está trucado; CD 14 Des o sepultado por 1d6 contundente y apresado." }, loot: { en: "An ancestral signet (50 gp) and 80 gp in grave-coin.", es: "Un sello ancestral (50 po) y 80 po en moneda de tumba." }, tac: { en: "Numbers, not toughness — the horde swamps a lone fighter. Fight in a doorway.", es: "Número, no dureza — la horda ahoga a un luchador solo. Pelea en un umbral." } },
      { name: { en: "Ritual Chancel", es: "Presbiterio Ritual" }, see: { en: "A defiled altar under guttering grave-lamps. Chalk sigils spiral out across the floor, half-finished.", es: "Un altar profanado bajo lámparas de tumba parpadeantes. Sigilos de tiza se despliegan por el piso, a medio terminar." }, trap: { en: "Warding glyph on the altar — DC 15 Arcana to read; crossing unbidden is DC 15 Wis or frightened 1 min.", es: "Glifo de protección en el altar — CD 15 Arcanos para leerlo; cruzar sin permiso es CD 15 Sab o asustado 1 min." }, loot: { en: "Ritual components (100 gp) and a scroll of the rite (clue to the climax).", es: "Componentes rituales (100 po) y un pergamino del rito (pista del clímax)." }, tac: { en: "Interrupting the ritual sigils here weakens the grave-lord's rite at the climax — a clever link worth flagging.", es: "Interrumpir los sigilos aquí debilita el rito del señor de las tumbas en el clímax — un vínculo astuto que conviene señalar." } },
      { name: { en: "Catacomb Stair", es: "Escalera de Catacumbas" }, see: { en: "A spiral of worn steps descends past shelf after shelf of the interred. Cold air pours up from below.", es: "Una espiral de peldaños gastados desciende ante estante tras estante de los sepultados. Aire frío sube desde abajo." }, trap: { en: "A trip-step near the bottom — DC 14 Perception; DC 14 Dex or tumble the flight for 2d6 bludgeoning.", es: "Un peldaño trampa cerca del fondo — CD 14 Percepción; CD 14 Des o rodar el tramo por 2d6 contundente." }, loot: { en: "Grave-tokens worth 70 gp wedged in the niches.", es: "Ofrendas de tumba por 70 po encajadas en los nichos." }, tac: { en: "The dead press from above and below on the stair — hold a landing so they can only come single-file.", es: "Los muertos presionan por arriba y por abajo en la escalera — mantén un rellano para que solo vengan en fila." } },
      { name: { en: "Embalming Room", es: "Sala de Embalsamado" }, see: { en: "Stone slabs, rusted tools, and jars of resin gone black. One slab's straps hang torn.", es: "Losas de piedra, herramientas oxidadas y tarros de resina ennegrecida. Las correas de una losa cuelgan desgarradas." }, trap: { en: "Spilled embalming reagents — a flame turns the floor into a 2d6 fire hazard for 1 round.", es: "Reactivos de embalsamar derramados — una llama vuelve el piso un peligro de fuego de 2d6 por 1 asalto." }, loot: { en: "Silvered instruments (60 gp) and a Potion of Healing in the cabinet.", es: "Instrumentos plateados (60 po) y una Poción de Curación en el gabinete." }, tac: { en: "The occupant rises off a slab when the party's backs are turned — a sudden flank to punish poor marching order.", es: "El ocupante se alza de una losa cuando el grupo da la espalda — un flanqueo súbito para castigar mala formación." } }
    ],
    climax: [{ name: { en: "Grave-Lord's Vault", es: "Cámara del Señor de las Tumbas" }, see: { en: "A domed burial vault. On a raised bier lies a crowned figure, and as you enter it opens its eyes and rises.", es: "Una cámara funeraria abovedada. En un catafalco elevado yace una figura coronada, y al entrar abre los ojos y se alza." }, trap: { en: "Grave-ward on the bier — striking the sleeper before it wakes triggers 3d6 necrotic burst (DC 15 Con half).", es: "Guarda de tumba en el catafalco — golpear al durmiente antes de que despierte lanza un estallido de 3d6 necrótico (CD 15 Con mitad)." }, loot: { en: "The grave-lord's regalia — a wondrous item — and 500 gp in tomb-treasure.", es: "Las insignias del señor de las tumbas — un objeto maravilloso — y 500 po en tesoro de tumba." }, tac: { en: "Climax. It commands the lesser dead and drains life; if the ritual chancel was disrupted it can't call reinforcements. Destroy its anchor to end it for good.", es: "Clímax. Comanda a los muertos menores y drena la vida; si se interrumpió el presbiterio, no puede llamar refuerzos. Destruye su ancla para acabarlo del todo." } }],
    secret: [{ name: { en: "Hidden Reliquary", es: "Relicario Oculto" }, see: { en: "Behind a false tomb-slab: a small sealed chamber, untouched by the rot outside. A record-stone rests on a plinth.", es: "Tras una losa falsa: una pequeña cámara sellada, intacta ante la podredumbre exterior. Una piedra-registro descansa en un pedestal." }, loot: { en: "A reliquary (guild of the dead): 300 gp, a Potion of Greater Healing, and the record-stone naming who broke the seal.", es: "Un relicario: 300 po, una Poción de Curación Mayor, y la piedra-registro que nombra a quien rompió el sello." }, tac: { en: "No fight. The record-stone is the ‘why’ and the key: it tells the party how to lay the grave-lord to rest for good.", es: "Sin combate. La piedra-registro es el ‘porqué’ y la llave: dice cómo dar descanso definitivo al señor de las tumbas." } }],
    hazard: [{ name: { en: "Flooded Crypt", es: "Cripta Inundada" }, see: { en: "Black water fills the sunken floor to the knee. Something disturbs its surface further in.", es: "Agua negra llena el piso hundido hasta la rodilla. Algo perturba su superficie más adentro." }, trap: { en: "Hidden drop-off under the water — DC 13 Perception; DC 13 Dex or plunge into a 10-ft sump (1d6).", es: "Desnivel oculto bajo el agua — CD 13 Percepción; CD 13 Des o caída a un sumidero de 3 m (1d6)." }, loot: { en: "A silt-caked reliquary worth 60 gp.", es: "Un relicario cubierto de limo por 60 po." }, tac: { en: "Optional. The water is difficult terrain and hides a lurker — an easy fight or a skippable breather.", es: "Opcional. El agua es terreno difícil y esconde a un acechador — un combate fácil o un respiro saltable." } }]
  };
  ROLE_PROSE.cave = {
    entry: [{ name: { en: "Cave Mouth", es: "Boca de la Cueva" }, see: { en: "Daylight gives out a few paces in. Gnawed bones and matted fur litter the entry, and small shapes scatter from the light.", es: "La luz del día se acaba a unos pasos. Huesos roídos y pelo apelmazado cubren la entrada, y formas pequeñas huyen de la luz." }, loot: { en: "A traveler's dropped purse (20 gp) among the bones.", es: "La bolsa perdida de un viajero (20 po) entre los huesos." }, tac: { en: "Warm-up. The vermin swarm and flee — teach the party the warren is alive and watching.", es: "Calentamiento. Las alimañas enjambran y huyen — enseña que la madriguera está viva y observa." } }],
    work: [
      { name: { en: "Webbed Hollow", es: "Hueco Entelarañado" }, see: { en: "Thick silk sheets the walls and ceiling, wrapping shapes that might once have moved. Strands twitch as you pass.", es: "Seda espesa cubre muros y techo, envolviendo formas que antes se movían. Las hebras se estremecen al pasar." }, trap: { en: "Sticky web curtain — DC 13 Perception; entering blind is DC 13 Dex or restrained until DC 12 Str.", es: "Cortina de tela pegajosa — CD 13 Percepción; entrar a ciegas es CD 13 Des o apresado hasta CD 12 Fue." }, loot: { en: "A cocooned victim's gear: 60 gp and a Potion of Healing.", es: "El equipo de una víctima encapullada: 60 po y una Poción de Curación." }, tac: { en: "The lurker drops from above onto a webbed target and poisons it. Burning the webs clears the terrain.", es: "El acechador cae desde arriba sobre un objetivo entelado y lo envenena. Quemar las telas despeja el terreno." } },
      { name: { en: "Den", es: "Guarida" }, see: { en: "A fouled nest of hides and dragged carcasses. The reek is overpowering and the far dark growls.", es: "Un nido inmundo de pieles y despojos arrastrados. El hedor es abrumador y la oscuridad del fondo gruñe." }, trap: { en: "Loose scree slope — DC 14 Dex crossing or slide prone into the den (rousing its keeper).", es: "Pendiente de grava suelta — CD 14 Des al cruzar o resbalar derribado a la guarida (despertando a su dueño)." }, loot: { en: "Swallowed valuables in the muck — 90 gp and a gold locket (25 gp).", es: "Objetos tragados en el fango — 90 po y un guardapelo de oro (25 po)." }, tac: { en: "The beast defends its nest ferociously and fights to the death here — use the terrain to split it from the party.", es: "La bestia defiende su nido con ferocidad y pelea a muerte aquí — usa el terreno para separarla del grupo." } },
      { name: { en: "Sinkhole", es: "Sumidero" }, see: { en: "The floor falls away into a wet pit ringed by a slick ledge. Wingbeats echo up from below.", es: "El piso cae a un foso húmedo rodeado de un borde resbaladizo. Aleteos resuenan desde abajo." }, trap: { en: "Crumbling ledge — DC 14 Dex or fall 15 ft (1d6) into the pit with whatever waits there.", es: "Borde que se desmorona — CD 14 Des o caída de 4,5 m (1d6) al foso con lo que aguarde ahí." }, loot: { en: "A hunter's lost pack at the pit bottom: 70 gp and a coil of silk rope.", es: "El morral perdido de un cazador al fondo: 70 po y una cuerda de seda." }, tac: { en: "Flyers use the vertical space — they harry from the dark and retreat upward. Ranged parties shine here.", es: "Los voladores usan el espacio vertical — hostigan desde la oscuridad y se retiran hacia arriba. Los grupos a distancia lucen aquí." } },
      { name: { en: "Fungal Gallery", es: "Galería de Hongos" }, see: { en: "Pale luminous fungus climbs the walls. A shallow pool reflects the glow, and the air is heavy and spore-thick.", es: "Hongos pálidos y luminosos trepan los muros. Una charca poco honda refleja el brillo, y el aire es pesado y cargado de esporas." }, trap: { en: "Burst-spore puffballs — DC 13 Perception; treading on one is DC 13 Con or poisoned 1 min.", es: "Bejines de esporas — CD 13 Percepción; pisar uno es CD 13 Con o envenenado 1 min." }, loot: { en: "Rare alchemical fungus worth 80 gp to the right buyer.", es: "Hongo alquímico raro por 80 po al comprador correcto." }, tac: { en: "The dweller camouflages against the fungus and ambushes — the pool is difficult terrain that funnels the fight.", es: "El morador se camufla entre los hongos y embosca — la charca es terreno difícil que encauza el combate." } },
      { name: { en: "Root Chamber", es: "Cámara de Raíces" }, see: { en: "Great tree-roots pierce the ceiling and cage the room. Something small chitters where they knot together.", es: "Grandes raíces perforan el techo y enjaulan la sala. Algo pequeño chirría donde se anudan." }, trap: { en: "Root snare — DC 13 Perception; stepping wrong is DC 13 Dex or hoisted and restrained (DC 12 Str to break free).", es: "Lazo de raíces — CD 13 Percepción; pisar mal es CD 13 Des o izado y apresado (CD 12 Fue para soltarse)." }, loot: { en: "A nest of swallowed coins and trinkets — 70 gp.", es: "Un nido de monedas y chucherías tragadas — 70 po." }, tac: { en: "Climbers use the roots for cover and high ground — smoke or fire flushes them down.", es: "Los trepadores usan las raíces como cobertura y altura — humo o fuego los hace bajar." } },
      { name: { en: "Underground Stream", es: "Arroyo Subterráneo" }, see: { en: "A cold stream cuts the cavern, loud enough to swallow footsteps. Pale things dart under the surface.", es: "Un arroyo frío corta la caverna, tan sonoro que traga las pisadas. Cosas pálidas se lanzan bajo la superficie." }, trap: { en: "Slick bank — DC 13 Dex or slip prone into the current and be swept 15 ft.", es: "Ribera resbaladiza — CD 13 Des o resbalar derribado a la corriente y ser arrastrado 4,5 m." }, loot: { en: "A drowned traveler's pack: 60 gp and a Potion of Water Breathing.", es: "El morral de un viajero ahogado: 60 po y una Poción de Respirar Bajo el Agua." }, tac: { en: "The current is difficult terrain and masks sound — the ambusher strikes from the water; ranged attackers own the far bank.", es: "La corriente es terreno difícil y enmascara el sonido — el emboscador ataca desde el agua; los atacantes a distancia dominan la orilla opuesta." } }
    ],
    climax: [{ name: { en: "The Deep Den", es: "La Guarida Honda" }, see: { en: "The warren opens into a high cavern strewn with the bones of its prey. Something enormous uncurls in the dark and turns to face you.", es: "La madriguera se abre a una caverna alta sembrada con los huesos de sus presas. Algo enorme se despliega en la oscuridad y se vuelve hacia ti." }, trap: { en: "Bone-strewn ground is difficult terrain; a false floor over a den-pit drops the unwary (DC 15 Dex, 2d6).", es: "El suelo de huesos es terreno difícil; un piso falso sobre un foso hunde al incauto (CD 15 Des, 2d6)." }, loot: { en: "The beast's hoard — a wondrous item swallowed long ago — and 500 gp in scattered valuables.", es: "El tesoro de la bestia — un objeto maravilloso tragado hace mucho — y 500 po en objetos dispersos." }, tac: { en: "Climax. It hits hard and grapples; if the den pack was thinned first, it fights alone. Fire and the cavern's ledges are your friends.", es: "Clímax. Golpea fuerte y apresa; si se diezmó la manada antes, pelea sola. El fuego y los salientes de la caverna son tus aliados." } }],
    secret: [{ name: { en: "Smuggler's Cache", es: "Alijo de Contrabandistas" }, see: { en: "Behind a curtain of roots: a dry crevice someone once used to hide goods. Crates sit stacked and forgotten.", es: "Tras una cortina de raíces: una grieta seca que alguien usó para esconder mercancía. Cajas apiladas y olvidadas." }, loot: { en: "The cache (DC 14 to find): 300 gp, a Potion of Greater Healing, and a map marking who stashed it here.", es: "El alijo (CD 14 para hallarlo): 300 po, una Poción de Curación Mayor, y un mapa que marca quién lo escondió aquí." }, tac: { en: "No fight. The map is the ‘why’ — it ties the warren to whoever's been feeding it, and points at a bigger job.", es: "Sin combate. El mapa es el ‘porqué’ — liga la madriguera con quien la ha estado alimentando, y apunta a un trabajo mayor." } }],
    hazard: [{ name: { en: "Choked Passage", es: "Pasaje Obstruido" }, see: { en: "The way narrows to a crawl through fallen rock. Skittering echoes from the cracks all around.", es: "El paso se estrecha a un gateo entre roca caída. Ecos de patas resuenan en las grietas alrededor." }, trap: { en: "Unstable ceiling — a loud noise brings it down; DC 14 Dex or 2d6 bludgeoning and half-buried.", es: "Techo inestable — un ruido fuerte lo derrumba; CD 14 Des o 2d6 contundente y medio sepultado." }, loot: { en: "A prospector's dropped satchel: 40 gp of ore samples.", es: "El zurrón perdido de un buscador: 40 po en muestras de mineral." }, tac: { en: "Optional. Cramped quarters and a swarm — an easy fight or a tension beat between bigger rooms.", es: "Opcional. Espacio angosto y un enjambre — un combate fácil o un momento de tensión entre salas mayores." } }]
  };
  ROLE_PROSE.cult = {
    entry: [{ name: { en: "Doorward", es: "Guardia de la Puerta" }, see: { en: "A plain undercroft lit by tallow candles. Hooded figures turn from a makeshift table, hands going to weapons.", es: "Una cripta sencilla iluminada por velas de sebo. Figuras encapuchadas se vuelven de una mesa improvisada, llevando las manos a las armas." }, loot: { en: "A collection plate (30 gp) and a wax-sealed pass-token for the inner doors.", es: "Un platillo de ofrendas (30 po) y una ficha sellada para las puertas interiores." }, tac: { en: "Warm-up. The doorwardens raise the alarm if they can — silence them fast or the sanctum is ready for you.", es: "Calentamiento. Los guardianes darán la alarma si pueden — silénciales rápido o el santuario te esperará listo." } }],
    work: [
      { name: { en: "Refectory", es: "Refectorio" }, see: { en: "Long tables set for a meal no one finished. Overturned benches and a spilled chalice suggest a hasty exit.", es: "Mesas largas dispuestas para una comida que nadie terminó. Bancos volcados y un cáliz derramado sugieren una salida apresurada." }, trap: { en: "Alarm bell-pull by the door — DC 14 Perception; triggering it summons help next round.", es: "Cuerda de campana de alarma junto a la puerta — CD 14 Percepción; activarla trae ayuda al asalto siguiente." }, loot: { en: "Offerings and plate worth 60 gp; a ledger of the cell's members.", es: "Ofrendas y vajilla por 60 po; un registro de los miembros de la célula." }, tac: { en: "The faithful fight in a mob and won't break — use the furniture as cover and choke points.", es: "Los fieles pelean en tropel y no huyen — usa el mobiliario como cobertura y puntos de embudo." } },
      { name: { en: "Cells", es: "Celdas" }, see: { en: "A row of barred cells, most empty. In one, a prisoner presses to the bars and hisses for silence.", es: "Una hilera de celdas enrejadas, casi todas vacías. En una, un prisionero se aprieta a los barrotes y pide silencio con un siseo." }, trap: { en: "Rigged lock on the far cell — DC 15 Thieves' Tools; forcing it is DC 14 Dex or 2d6 piercing.", es: "Cerradura trucada en la celda del fondo — CD 15 Herramientas de Ladrón; forzarla es CD 14 Des o 2d6 perforante." }, loot: { en: "The prisoner (freed) reveals the celebrant's weakness; a guard's purse holds 50 gp.", es: "El prisionero (liberado) revela la debilidad del oficiante; la bolsa de un guardia guarda 50 po." }, tac: { en: "Freeing and protecting the prisoner is the non-violent thread — they can talk down part of the choir.", es: "Liberar y proteger al prisionero es el hilo no violento — puede convencer a parte del coro." } },
      { name: { en: "Scriptorium", es: "Escritorio" }, see: { en: "Slanted desks buried in copied pages. Ink pots have frozen mid-stroke, and one candle still burns.", es: "Pupitres inclinados sepultados en páginas copiadas. Los tinteros se han secado a media pincelada, y una vela aún arde." }, trap: { en: "Glyph-warded folio — opening it wrong is DC 15 Wis or 3d6 psychic and stunned 1 round.", es: "Folio protegido con glifo — abrirlo mal es CD 15 Sab o 3d6 psíquico y aturdido 1 asalto." }, loot: { en: "A spell scroll and heretical texts worth 90 gp; the ritual's true name (weakens the climax).", es: "Un pergamino de conjuro y textos heréticos por 90 po; el nombre verdadero del rito (debilita el clímax)." }, tac: { en: "Learning the rite's true name here lets a PC disrupt the celebrant at the climax — a clever link worth flagging.", es: "Aprender aquí el nombre verdadero del rito permite a un PJ interrumpir al oficiante en el clímax — un vínculo astuto a señalar." } },
      { name: { en: "Reliquary of the Choir", es: "Relicario del Coro" }, see: { en: "A brazier-lit shrine of stitched trophies. A great cauldron simmers with something that hums under the ear.", es: "Un santuario iluminado por braseros de trofeos cosidos. Un gran caldero borbotea con algo que zumba bajo el oído." }, trap: { en: "The cauldron's fumes — lingering is DC 14 Con or poisoned; dumping it is a loud, useful sabotage.", es: "Los vapores del caldero — permanecer es CD 14 Con o envenenado; volcarlo es un sabotaje ruidoso y útil." }, loot: { en: "Ritual silver (120 gp) and a Potion of Greater Healing.", es: "Plata ritual (120 po) y una Poción de Curación Mayor." }, tac: { en: "The zealot here fights recklessly to protect the cauldron — destroying it slows the rite next door.", es: "El fanático aquí pelea sin cautela para proteger el caldero — destruirlo retrasa el rito de al lado." } },
      { name: { en: "Vestry", es: "Sacristía" }, see: { en: "Racks of stained robes and ritual masks. A basin of dark water reflects nothing that's there.", es: "Percheros de túnicas manchadas y máscaras rituales. Una pila de agua oscura no refleja nada de lo que hay." }, trap: { en: "A warded chest among the robes — DC 15 to open; failure is DC 14 Con or 2d6 necrotic.", es: "Un cofre protegido entre las túnicas — CD 15 para abrirlo; fallar es CD 14 Con o 2d6 necrótico." }, loot: { en: "Ceremonial regalia worth 80 gp and a mask that conceals identity.", es: "Ornamentos ceremoniales por 80 po y una máscara que oculta la identidad." }, tac: { en: "The faithful don masks and blend with the racks, ambushing as a group — hard to tell friend from foe.", es: "Los fieles se enmascaran y se confunden con los percheros, emboscando en grupo — cuesta distinguir amigo de enemigo." } },
      { name: { en: "Meditation Cells", es: "Celdas de Meditación" }, see: { en: "A honeycomb of tiny cells, each with a guttered candle and chalked prayers. One candle is freshly lit.", es: "Un panal de celdas diminutas, cada una con una vela consumida y oraciones en tiza. Una vela está recién encendida." }, trap: { en: "A collapsing false wall — DC 14 Perception; DC 14 Dex or 2d6 bludgeoning and pinned.", es: "Un muro falso que se derrumba — CD 14 Percepción; CD 14 Des o 2d6 contundente y atrapado." }, loot: { en: "Hidden offerings behind a loose brick: 70 gp and a spell scroll.", es: "Ofrendas ocultas tras un ladrillo suelto: 70 po y un pergamino de conjuro." }, tac: { en: "A zealot waits in trance and erupts when disturbed — isolate the cells so only one foe engages at a time.", es: "Un fanático espera en trance y estalla al ser perturbado — aísla las celdas para que solo un enemigo entable combate a la vez." } }
    ],
    climax: [{ name: { en: "The Sanctum", es: "El Santuario" }, see: { en: "A pillared shrine around a glowing focus on the central altar. A robed celebrant lifts both hands, and the air itself leans toward the light.", es: "Un santuario de columnas en torno a un foco luminoso sobre el altar central. Un oficiante de túnica alza ambas manos, y el aire mismo se inclina hacia la luz." }, trap: { en: "Binding circle on the floor — crossing it uninvited is DC 15 Cha or restrained by unseen hands (3d6 if the rite completes).", es: "Círculo de atadura en el piso — cruzarlo sin invitación es CD 15 Car o apresado por manos invisibles (3d6 si el rito se completa)." }, loot: { en: "The Hollow Focus — a wondrous item — and the choir's 500 gp offering-hoard.", es: "El Foco Hueco — un objeto maravilloso — y el tesoro de ofrendas de 500 po del coro." }, tac: { en: "Climax. The celebrant buffs the faithful and completes the rite in 3 rounds. Shatter the focus or speak the true name to stop it cold.", es: "Clímax. El oficiante potencia a los fieles y completa el rito en 3 asaltos. Destroza el foco o pronuncia el nombre verdadero para detenerlo en seco." } }],
    secret: [{ name: { en: "Celebrant's Cell", es: "Celda del Oficiante" }, see: { en: "Behind a hanging tapestry: a spare private cell. A journal lies open, and a lockbox is bolted beneath the cot.", es: "Tras un tapiz colgante: una celda privada y austera. Un diario abierto, y una caja fuerte atornillada bajo el catre." }, loot: { en: "The lockbox (DC 15): 300 gp, a signet, and the journal — who funds the choir and what the rite truly opens.", es: "La caja (CD 15): 300 po, un sello, y el diario — quién financia al coro y qué abre en verdad el rito." }, tac: { en: "No fight. The journal is the ‘why’: it turns a raid into a choice and points at a patron above the celebrant.", es: "Sin combate. El diario es el ‘porqué’: convierte la redada en una decisión y apunta a un mecenas sobre el oficiante." } }],
    hazard: [{ name: { en: "Sump", es: "Sumidero" }, see: { en: "A dank overflow chamber knee-deep in runoff. Candle-stubs float in the murk, and something ripples away from your light.", es: "Una cámara de desagüe húmeda con agua hasta la rodilla. Cabos de vela flotan en la turbiedad, y algo se aleja de tu luz." }, trap: { en: "Submerged grating drop — DC 13 Perception; DC 13 Dex or fall into a 10-ft cistern (1d6).", es: "Rejilla sumergida — CD 13 Percepción; CD 13 Des o caída a una cisterna de 3 m (1d6)." }, loot: { en: "A votary's dropped offering-purse: 40 gp.", es: "La bolsa de ofrenda perdida de un devoto: 40 po." }, tac: { en: "Optional. Difficult terrain and a lurker — an easy fight or a skippable breather.", es: "Opcional. Terreno difícil y un acechador — un combate fácil o un respiro saltable." } }]
  };

  DDG.MON = MON;
  DDG.THEMES = THEMES;
  DDG.ROLE_PROSE = ROLE_PROSE;
  DDG.monEntry = monEntry;
  if (typeof module !== "undefined" && module.exports) module.exports = { MON: MON, THEMES: THEMES, ROLE_PROSE: ROLE_PROSE };
})(typeof window !== "undefined" ? window : globalThis);
